translation in French of the tool_for_renewal_en.md
monero-ecosystem/outreach-docs pull request #216
Opened 2020-07-17 02:48 UTC by Tomahna81

This is a translation in French of https://www.monerooutreach.org/stories/the-tool-for-renewal.html

Open for review.

2020-08-03 14:10 UTC, JLB-XMR commented
Following the request of @lh1008, I'm ready for the review.

2020-08-03 16:13 UTC, lh1008 commented
Thank you @JLB-XMR for taking the review.

2020-08-04 03:51 UTC, Tomahna81 commented
> Hello @Tomahna81
> 
> Please change the files name to, `tool_for_renewal_fr.md`. That way we keep consistency throughout the repository. The English file's name is, `tool_for_renewal_en..md`, what changes are the language extensions.
> 
> Thank you.

Hi, renaming is done now. Waiting for the comments from the reviewer.

Cheers.

2020-08-05 15:03 UTC, lh1008 commented
Hey @JLB-XMR 

Like I told you in the chat, you will have to create a new branch for the wallet_primer_fr.md file. Let me know if you need any help with this. We will also delete the unnecessary commits :).

2020-08-05 21:09 UTC, Tomahna81 commented
> Hey @JLB-XMR
> 
> Like I told you in the chat, you will have to create a new branch for the wallet_primer_fr.md file. Let me know if you need any help with this. We will also delete the unnecessary commits :).

Hi lh1008,
Thanks for the message. I think this was for me (@Tomahna81) and not to @JLB-XMR. In any case, I have removed the wallet_primer_fr.md from this branch. As you advised me, wallet_primer_fr.md is another translation that should go on an independent branch.

2020-08-16 16:09 UTC, lh1008 commented
Hey @Tomahna81,

Yeah, the past message was for you, oups. I'm currently speaking with the reviewer and helping him start the workflow through GitHub, I believe this week we should have started already so we can continue with the next PR.

2020-11-09 03:31 UTC, Hsterofemia commented
[Review_the tool_for_renewal_fr.txt](https://github.com/monero-ecosystem/outreach-docs/files/5507961/Review_the.tool_for_renewal_fr.txt)
Hi Guys, please find attached the recommended comments and changes. The text is great, these are minor changes. Let me know if this is the best format to communicate the changes.

Cheers

2020-11-09 20:10 UTC, Hsterofemia commented on monero-outreach-docs/translations/fr/storyboard/Translations-fr-tool_for_renewal.md
> +Cependant, étant tout récent, Bitcoin avait des défauts techniques, incluant une faible confidentialité. Et alors un autre groupe ou personne sous le pseudonyme de Nicolas van Saberhagen développa le
Chainalysis a récemment déclarée dans un webinaire public ==> Chainalysis a récemment **déclaré** dans un webinaire public. La version originale était la bonne, le PP ne s'accorde pas ici car le COD est placé après

2020-11-10 00:02 UTC, Hsterofemia requested changes
Review with corrections, mostly grammar, syntax and conjugation. format is:
[original text] ==> [Modification ; explanation for the suggested modification]

2020-11-10 02:47 UTC, Hsterofemia commented
Hi @Tomahna81, I think you maybe missed some comments on lines 17 to 37.

2020-11-10 04:22 UTC, OthmanB commented on monero-outreach-docs/translations/fr/storyboard/Translations-fr-tool_for_renewal.md
> +Cependant, étant tout récent, Bitcoin avait des défauts techniques, incluant une faible confidentialité. Et alors un autre groupe ou personne sous le pseudonyme de Nicolas van Saberhagen développa le
Ok. Pas de soucis.

2020-11-17 22:16 UTC, lh1008 commented
@Hsterofemia could you please approve the changes so we can merge this pull request? :)

2020-11-17 22:19 UTC, lh1008 commented
@Tomahna81 once the commits are approved we will have to remove unnecessary commits and squash into one commit the rest. Let me know once this is approved so I can help you out. :)

2020-11-18 01:45 UTC, Hsterofemia approved these changes
Changes approved.

2020-11-18 01:45 UTC, Hsterofemia approved these changes
Changes approved

2020-11-18 01:46 UTC, Hsterofemia submitted a review, later dismissed

2020-11-20 10:50 UTC, erciccione requested changes

2020-11-20 10:50 UTC, erciccione commented on monero-outreach-docs/translations/fr/storyboard/Translations-fr-tool_for_renewal.md
> +- [Qu’est-ce que Monero ? (Site web officiel)](https://web.getmonero.org/fr/get-started/what-is-monero/)
```suggestion
- [Qu’est-ce que Monero ? (Site web officiel)](https://www.getmonero.org/fr/get-started/what-is-monero/)
```

2020-11-20 10:50 UTC, erciccione commented on monero-outreach-docs/translations/fr/storyboard/Translations-fr-tool_for_renewal.md
> +- [Pourquoi Monero plutôt que Bitcoin (Monero.how)](monero.how/why-monero-vs-bitcoin)
```suggestion
- [Pourquoi Monero plutôt que Bitcoin (Monero.how)](https://monero.how/why-monero-vs-bitcoin)
```

2020-11-20 10:50 UTC, erciccione commented on monero-outreach-docs/translations/fr/storyboard/Translations-fr-tool_for_renewal.md
> +- [Pourquoi Monero ? (Monero World)](moneroworld.com/whymonero.html)
```suggestion
- [Pourquoi Monero ? (Monero World)](https://moneroworld.com/whymonero.html)
```

2020-11-20 10:50 UTC, erciccione commented on monero-outreach-docs/translations/fr/storyboard/Translations-fr-tool_for_renewal.md
> +- [Monero signifie Argent : Cryptocurrency 101, en direct de Leipzig (Documentaire)](communityworkgroup.org/monero-means-money)
```suggestion
- [Monero signifie Argent : Cryptocurrency 101, en direct de Leipzig (Documentaire)](https://communityworkgroup.org/monero-means-money)
```

2020-11-20 10:50 UTC, erciccione commented on monero-outreach-docs/translations/fr/storyboard/Translations-fr-tool_for_renewal.md
> +- [“Mastering Monero” (Livre)](masteringmonero.com)
```suggestion
- [“Mastering Monero” (Livre)](https://masteringmonero.com)
```

2020-11-20 10:50 UTC, erciccione commented on monero-outreach-docs/translations/fr/storyboard/Translations-fr-tool_for_renewal.md
> +- [“Zero to Monero” (Livre)](getmonero.org/fr/library/Zero-to-Monero-2-0-0.pdf)
```suggestion
- [“Zero to Monero” (Livre)](https://www.getmonero.org/fr/library/Zero-to-Monero-2-0-0.pdf)
```

2020-11-20 10:50 UTC, erciccione commented on monero-outreach-docs/translations/fr/storyboard/Translations-fr-tool_for_renewal.md
> +- [https://web.getmonero.org/fr/community/merchants/index.html](https://web.getmonero.org/fr/community/merchants/index.html)
```suggestion
- [https://web.getmonero.org/fr/community/merchants/index.html](https://www.getmonero.org/fr/community/merchants/index.html)
```

2020-11-20 10:50 UTC, erciccione commented on monero-outreach-docs/translations/fr/storyboard/Translations-fr-tool_for_renewal.md
> +- https://web.getmonero.org/community/merchants/
```suggestion
- https://www.getmonero.org/community/merchants/
```

2020-11-20 10:51 UTC, erciccione commented
> Please change the files name to, tool_for_renewal_fr.md

This still needs to be changed.

2020-11-26 05:47 UTC, lh1008 submitted a review, later dismissed
This looks good. :)

2020-11-26 11:51 UTC, erciccione requested changes
> Please change the files name to, tool_for_renewal_fr.md

2020-11-27 12:53 UTC, erciccione approved these changes
Looks ok.

2020-11-27 22:57 UTC, merged