Translation pt-br
monero-ecosystem/outreach-docs pull request #240
Opened 2020-09-09 01:04 UTC by nelsonrenan

2020-09-09 19:08 UTC, lh1008 commented
The same here @nelsonrenan. Please add the title of the article you worked upon. Thanks :)

2020-09-11 19:36 UTC, lh1008 commented
Pinging @botoserelepe @netrik182 for review. If anyone of you can helps us out would be of great help :).

2020-09-20 23:22 UTC, botoserelepe requested changes
@lh1008 review done :)
@nelsonrenan good job! Very nice translation! I have just made some suggestions to change a few words.

2020-09-20 23:22 UTC, botoserelepe commented on monero-outreach-docs/translations/pt-br/archive/we_accept_monero_pt-br.md
> +A missão, você deveria escolher aceitá-la, é contatar seu comerciante favorito e perguntar a ele se ele considerou aceitar Monero, porque esse seria seu método de pagamento favorito. Ele poderia dize
```suggestion
A missão, caso você opte por cumpri-la, é contatar seu comerciante favorito e perguntar a ele se ele considerou aceitar Monero, porque esse seria seu método de pagamento favorito. Ele pode dizer sim, ele pode dizer não, mas finalmente você os fez pensar sobre o assunto. Não será a última vez que eles ouvem sobre o Monero, mas pode ser a primeira.

```

2020-09-20 23:22 UTC, botoserelepe commented on monero-outreach-docs/translations/pt-br/archive/we_accept_monero_pt-br.md
> +No mercado a sabedoria popular diz que alguém precisa ver a mensagem sete vezes antes de tomar consciência. Essa é uma regra polegar para publicidade, mas nós não estamos esperando encorajar uma conv
```suggestion
No mercado a sabedoria popular diz que alguém precisa ver a mensagem sete vezes antes de tomar consciência dela. Essa é uma regra geral para publicidade, mas nós não estamos esperando encorajar uma conversa com comerciantes. Uma boa conversa vale facilmente por sete visitas nos anúncios. Pesquisas têm descoberto que pessoas que conhecem uma organização são cinco vezes mais propensas a ter uma opinião favorável sobre ela. Em outras palavras, quanto mais você falar sobre Monero, mais as pessoas irão gostar.

```

2020-09-20 23:22 UTC, botoserelepe commented on monero-outreach-docs/translations/pt-br/archive/we_accept_monero_pt-br.md
> +Além disso temos criado este folheto do tamanho de uma nota de dólar que você pode imprimir e guardar em sua carteira para quando você estiver andando pelo mundo. Esta peça foca nos três recursos do
```suggestion
Além disso temos criado este folheto do tamanho de uma nota de dólar que você pode imprimir e guardar em sua carteira para quando você estiver andando pelo mundo. Esta folha foca nos três recursos do Monero que são mais importantes para os pequenos donos de negócios e os convida a aprender mais em nossas páginas [Serviços Monero para comerciantes](https://www.monerooutreach.org/merchants/).

```

2020-09-20 23:22 UTC, botoserelepe commented on monero-outreach-docs/translations/pt-br/archive/we_accept_monero_pt-br.md
> +Você pode fazer o download do arquivo pronto para impressão em [WhenYouAcceptMonero-en-WalletBuckslip.pdf](https://static.monerooutreach.org/img/MoneroMerchants/WhenYouAcceptMonero-en-WalletBuckslip.
I would remove "vá com Deus", as a personal choice not to involve religion with financial matters, but it is totally up to you :)

2020-10-07 20:11 UTC, lh1008 approved these changes
Everything looks fine. Sorry I took so long to be approved.

2020-10-09 07:01 UTC, merged