Translation of triptych pt-br
monero-ecosystem/outreach-docs pull request #248
Opened 2020-10-19 00:23 UTC by botoserelepe

@lh1008 here is the translation.

pinging @netrik182 @nelsonrenan for review.

2020-10-19 00:26 UTC, netrik182 commented on monero-outreach-docs/translations/pt-br/archive/triptych_pt-br.md
> +O movimento de Monero entre as chaves públicas é mantido em segredo agora usando o que são chamadas de assinaturas criptográficas em anel. Com essa abordagem, a chave pública para uma TXO real é esco
Let me know what you think about this suggestion below. 

```suggestion
Hoje, o movimento de Monero entre as chaves públicas é mantido em segredo usando um mecanismo chamado de assinaturas criptográficas em anel. Com essa abordagem, a chave pública para uma TXO real é escondida colocando-a junto com chamarizes (também chamados de mixins). Olhando para a transação, não há maneira de dizer se a TXO real está sendo usada ou se é algum dos chamarizes. Você pode ver exemplos de entradas e saídas de TXOs olhando uma transação em um explorador da blockchain do Monero, como [moneroblocks.info](https://moneroblocks.info/) ou [xmrchain.net](https://xmrchain.net/).
```

2020-10-19 00:30 UTC, netrik182 commented on monero-outreach-docs/translations/pt-br/archive/triptych_pt-br.md
> +Os algoritmos fundamentais das assinaturas em anel também melhoraram. O whitepaper original do CryptoNote fornecia um esquema de assinatura em anel diferente da implementação atual mais eficiente bas
```suggestion
Os algoritmos fundamentais das assinaturas em anel também melhoraram. O whitepaper original do CryptoNote fornecia um esquema de assinatura em anel diferente da implementação atual, mais eficiente, que basea-se em assinaturas de Grupo Anônimo Espontâneo Multicamadas Conectável (MLSAG, do inglês Multilayered Linkable Spontaneous Anonymous Group). Uma melhoria muito esperada, chamada de assinaturas em Grupo Anônimo Espontâneo Conciso Conectável (CLSAG, do inglês Concise Linkable Spontaneous Anonymous Group), virá em breve e espera-se que ela reduza o tamanho total da uma transação para 1/4 e o tempo de verificação em aproximadamente 1/10 (para uma transação de 2 entradas e 2 saídas).
```

2020-10-19 00:34 UTC, netrik182 commented on monero-outreach-docs/translations/pt-br/archive/triptych_pt-br.md
> +Porém, a ocultação do remetente de Monero não é perfeita. Dez chamarizes nem sempre são suficientes porque alguns TXOs aleatórios podem ser identificáveis. Eles podem já ter sido gastos anteriormente
Maybe it's better to explain wait "timing" means here. See my suggestion:

```suggestion
Porém, a ocultação do remetente de Monero não é perfeita. Dez chamarizes nem sempre são suficientes porque alguns TXOs aleatórios podem ser identificáveis. Eles podem já ter sido gastos anteriormente com conhecimento público. A existência de listas de excluídos mostra que isso é um problema potencial e dá uma alternativa àqueles que têm motivação e iniciativa para adicionar a lista às suas carteiras. E existem outras formas de identificar chamarizes, incluindo vincular TXOs à pools e corretoras, estimando a sua validade em outras transações, e usando análises probabilísticas de timing (que correlaciona o tempo/hora das transações).
```

2020-10-19 00:46 UTC, netrik182 requested changes
Very nice work @botoserelepe. This text is somewhat technical but you mastered it. Congrats!

I added a few suggestions and corrections. Please take a look and let me know if you don't agree with them.

2020-10-19 00:46 UTC, netrik182 commented on monero-outreach-docs/translations/pt-br/archive/triptych_pt-br.md
> +Bem, para o algoritmo MLSAG/CLSAG usado pelo Monero, tanto o tamanho da transação quando o tempo de processamento aumenta linearmente com o número de chamarizes. Usar 10 chamarizes balanceia a necess
```suggestion
Bem, para o algoritmo MLSAG/CLSAG usado pelo Monero, tanto o tamanho da transação quando o tempo de processamento aumenta linearmente com o número de chamarizes. Usar 10 chamarizes balanceia a necessidade de privacidade com a necessidade de uma blockchain menor e um tempo de processamento mais rápido. Aumentar o número de chamarizes ajudaria na privacidade, mas também inflaria o tamanho da transação do Monero, que já é algumas vezes maior que a do Bitcoin, e atolaria as carteiras que estão fazendo validação.
```

2020-10-19 00:46 UTC, netrik182 commented on monero-outreach-docs/translations/pt-br/archive/triptych_pt-br.md
> +Enfrentando esses desafios está o Triptych, um novo algoritmo para assinaturas em anel desenvolvido por Sarang Noether e Brandon Goodell dos Laboratórios de Pesquisa Monero (MRL, do inglês Monero Res
```suggestion
Enfrentando esses desafios está o Triptych, um novo algoritmo para assinaturas em anel desenvolvido por Sarang Noether e Brandon Goodell dos Laboratórios de Pesquisa Monero (MRL, do inglês Monero Research Labs) com ajuda do parceiro externo Arthur Blue (RandomRun). Com o Triptych, o tamanho da assinatura em anel cresce logaritmicamente em vez de linearmente. O crescimento logarítmico é muito devagar, o melhor padrão de crescimento sem precisar confiar em alguém para usar e depois destruir a aleatoriedade durante a configuração (como foi feito pela Zcash). O tempo de verificação ainda cresce linearmente com o número de chamarizes no Triptych, mas a verificação pode ser feita em lote e avaliada usando algoritmos especiais, os quais fornecem maior velocidade.
```

2020-10-19 00:46 UTC, netrik182 commented on monero-outreach-docs/translations/pt-br/archive/triptych_pt-br.md
> +O Triptych supera vários desafios de assinaturas em anel aplicadas ao Monero. Ele fornece capacidade de conexões. A técnica de assinaturas em anel do Monero precisa bloquear a reutilização de chaves
A slight and optional change but makes sense, I think.

```suggestion
O Triptych supera vários desafios de assinaturas em anel aplicadas ao Monero. Ele fornece capacidade de conexões. A técnica de assinaturas em anel do Monero precisa bloquear a reutilização de chaves públicas legítimas de forma a prevenir que um TXO seja gasto mais de uma vez (o tão chamado gasto duplo). O Tritych faz isso usando rótulos de associação que são similares às atuais imagens chave. O Triptych também reforça o uso de transações confidenciais para esconder quantidades de Monero. Dados especiais chamados de chaves de comprometimento permitem a comprovação de que os valores do Monero em uma transação são legítimos, sem divulgar esses valores. Essas chaves de comprometimento com as chaves de assinatura e os rótulos de associação são três componentes que dão origem ao nome Triptych, significando algo que possui três partes.
```

2020-10-19 00:46 UTC, netrik182 commented on monero-outreach-docs/translations/pt-br/archive/triptych_pt-br.md
> +Mas ainda tem trabalho, já que é necessária uma validação rigorosa para novos algoritmos como o Triptych entrarem no código base do Monero. Mesmo que o paper do algoritmo Triptych já tenha sido revis
```suggestion
Mas ainda existe trabalho a ser feito, já que é necessária uma validação rigorosa para novos algoritmos como o Triptych entrarem no código base do Monero. Mesmo que o paper do algoritmo Triptych já tenha sido revisado (e aceito no ESORICS CBT 2020 Workshop), o Tritych ainda pode ser melhorado com modificações nos algoritmos e no software que implementa esses algoritmos. E a implementação pode ser ainda mais otimizada para reduzir o tempo de validação. Gastar esforços com o Triptych substitui a necessidade de trabalhar em alternativas.
```

2020-10-26 17:04 UTC, lh1008 commented
Hello,

@botoserelepe, @netrik182 did some suggestions to the translation. Pinging you so you can take a look at them.

2020-10-27 01:42 UTC, botoserelepe commented
@lh1008 corrections were done!
@netrik182 thanks for the review, I accepted all your suggestions. :)

2020-11-09 18:41 UTC, lh1008 approved these changes
Hey @botoserelepe @netrik182 

Great work, thank you :). Everything looks good, approved.

2020-11-10 11:17 UTC, merged