Translation Dandelion_en for Dandelion_pt-br
monero-ecosystem/outreach-docs pull request #251
Opened 2020-10-30 15:14 UTC by nelsonrenan

2020-11-09 18:43 UTC, lh1008 commented
Hey @nelsonrenan thank you for the translation. Pinging @botoserelepe @netrik182 for review.

2020-11-19 19:01 UTC, botoserelepe requested changes
@nelsonrenan very nice translation! :) I opted to keep the name "Dandelion" without translation, as it is a software name. Besides that, I proposed only small changes in your text, I hope you agree with them.

2020-11-20 21:48 UTC, nelsonrenan commented on monero-outreach-docs/translations/pt-br/archive/dandelion_pt-br.md
> +Monero fica em sua rede de comunicação par a par. A rede de computadores que armazenam a Blockchain – chamados de nós – compartilham informações que suprem a rede Monero, como os endereços de nós, da
Perfect! I had thought about it, but I decided to translate and wait for a suggestion in the review.

2020-11-27 22:59 UTC, lh1008 commented
hey @nelsonrenan, is everything ready or does it need something else?

2020-11-29 10:57 UTC, nelsonrenan commented
Hi @lh1008. Yes, is everything ready.

2020-12-05 18:18 UTC, netrik182 approved these changes
First line still has the original title. Besides that, should be good to go.

2020-12-08 21:20 UTC, nelsonrenan commented
Hi @netrik182. The first line will remain as in the original. As recommended by @botoserelepe .

2020-12-09 22:16 UTC, botoserelepe approved these changes

2020-12-11 19:02 UTC, lh1008 requested changes
Before merging @nelsonrenan could you please squash commits and make only one. :)

2020-12-12 09:21 UTC, erciccione commented
@lh1008 It's ok, i can squash the commits as i usually do for the PRs on this repo. I just need an approval.

2020-12-16 19:03 UTC, lh1008 approved these changes
Approved

2020-12-17 11:19 UTC, merged