"How to Buy" - Chinese translation
monero-ecosystem/outreach-docs pull request #257
Opened 2020-12-13 12:30 UTC by 333x

My taiga.getmonero.org name: ie333

2020-12-28 17:07 UTC, lh1008 commented
@333x could you please send me the email you used to open your taiga account to paintluis[at]protonmail[dot]com?

2021-01-10 16:56 UTC, 333x commented
> @333x could you please send me the email you used to open your taiga account to paintluis[at]protonmail[dot]com?

I had sent the email a week ago.
My Taiga account email: ie333[at]icloud[dot]com 
My Taiga account username: ie333

2021-01-21 13:49 UTC, lh1008 commented
@blackey added as reviewer for this task.

https://taiga.getmonero.org/project/xmrhaelan-monero-public-relations/task/309

2021-01-22 02:04 UTC, jianjunchu requested changes
Some sentences are not fluent, and suggestions for revision are given

2021-01-22 02:04 UTC, jianjunchu commented on monero-outreach-docs/translations/zh-hans/archive/how_to_buy_zh-hans.md
> +Paypal、Apple Pay、Google Pay、Venmo或西联汇款这类型的服务并不私密，而且可能很昂贵。这些汇款服务也会有自己的服务条款和政策，可能会给你带来额外的风险。尤其是Paypal，XMR卖家需要小心，因为交易可能会被逆转，而PayPal的政策是在发生纠纷时站在买方一边。在一个骗局的例子中，爱丽丝同意以X美元从鲍勃那里购买1个XMR。爱丽丝通过Paypal向鲍勃发送了X美元，然
“Paypal、Apple Pay、Google Pay、Venmo或西联汇款这类型的服务并不私密，而且可能很昂贵” -> "使用 Paypal、Apple Pay、Google Pay、Venmo或西联汇款这类型的服务并不会保护隐私，而且可能很昂贵"

2021-01-23 14:59 UTC, lh1008 commented
Pinging @333x :). The review has been done.

2021-01-24 08:52 UTC, 333x commented
> Pinging @333x :). The review has been done.

Updated.

2021-01-26 01:35 UTC, lh1008 commented
@jianjunchu could you please approve the changes so we can merge them? :)

2021-01-26 08:45 UTC, jianjunchu approved these changes

2021-01-29 19:31 UTC, lh1008 approved these changes
Thank you @333x and  @jianjunchu 

This should be ready to merge.

2021-01-30 11:18 UTC, merged