"How to accept Monero" - Portuguese Translation
monero-ecosystem/outreach-docs pull request #261
Opened 2020-12-16 22:15 UTC by 0xyw

2020-12-22 19:34 UTC, lh1008 commented
Review assigned to @botoserelepe :+1:

2020-12-24 12:16 UTC, saxocat submitted a review, later dismissed
Hi,
I didn't find any errors.
You're free to publish!

Merry Christmas and a Happy New Year!

2021-01-07 16:08 UTC, botoserelepe requested changes
@lh1008 review done! Sorry for the late answer, I had forgotten about it after the Xmas holidays! My fault.
@0xyw Awesome translation! I only did some minor suggestions and corrections.
Some of the links of this article might exist in Portuguese, so I think it is useful to check them before publishing.

2021-01-07 17:27 UTC, saxocat commented
Hey!
If needed I can also write the european portuguese (pt_PT) version since some of the semantics change.
Let me know if that would help!

2021-01-11 21:04 UTC, 0xyw commented on monero-outreach-docs/translations/pt-br/merchants/how_to_accept_monero_pt_br.md
> +Ilustrado por:
there is no info about the illustrator.
https://github.com/monero-ecosystem/outreach-docs/blob/master/monero-outreach-docs/en/merchants/how_to_accept_monero_en.md

2021-01-11 21:13 UTC, 0xyw commented
> Hey!
> If needed I can also write the european portuguese (pt_PT) version since some of the semantics change.
> Let me know if that would help!

tens telegram?

2021-01-11 21:16 UTC, 0xyw commented
nice review. I think it's ready for merge @lh1008 @erciccione

2021-01-11 21:19 UTC, 0xyw commented on monero-outreach-docs/translations/pt-br/merchants/how_to_accept_monero_pt_br.md
> +Se você ainda não tem uma carteira/endereço Monero então é melhor criar uma primeiro. As carteiras Monero GUI/CLI oficiais de [getmonero.org/downloads](https://www.getmonero.org/pt-br/downloads/index
I did not find it.

2021-01-11 21:38 UTC, botoserelepe submitted a review, later dismissed

2021-01-11 21:42 UTC, 0xyw commented on monero-outreach-docs/translations/pt-br/merchants/how_to_accept_monero_pt_br.md
> +Se você ainda não tem uma carteira/endereço Monero então é melhor criar uma primeiro. As carteiras Monero GUI/CLI oficiais de [getmonero.org/downloads](https://www.getmonero.org/pt-br/downloads/index
true, but the article isn't available on the official website

```suggestion
Se você ainda não tem uma carteira/endereço Monero então é melhor criar uma primeiro. As carteiras Monero GUI/CLI oficiais de [getmonero.org/downloads](https://www.getmonero.org/pt-br/downloads/index.html) são sempre recomendadas. Além disso, esse guia irá indicar carteiras mobile e você pode achar informação sobre elas na página de [Configuração da Carteira Monero](https://github.com/monero-ecosystem/outreach-docs/blob/master/monero-outreach-docs/translations/pt-br/storyboard/wallet_quickstart_pt-br.md). 
```

2021-01-11 21:44 UTC, 0xyw commented on monero-outreach-docs/translations/pt-br/merchants/how_to_accept_monero_pt_br.md
> +Pode haver um lag na verificação de novas transações, geralmente 90 segundos. Portanto, dependendo de quando sua carteira verifica se há novas transações e com que rapidez sua transação entra em bloc
```suggestion
Pode haver um atraso na verificação de novas transações, geralmente 90 segundos. Portanto, dependendo de quando sua carteira verifica se há novas transações e com que rapidez sua transação entra em blocos minerados, o tempo real esperado antes que ela apareça em sua carteira é de 4 a 12 minutos. Para uma análise mais aprofundada do processo de transação do Monero e da duração média, visite [monero.how/how-long-do-monero-transactions-take](https://www.monero.how/how-long-do-monero-transactions-take).
```

2021-01-11 22:01 UTC, saxocat commented
> > Hey!
> > If needed I can also write the european portuguese (pt_PT) version since some of the semantics change.
> > Let me know if that would help!
> 
> tens telegram?

Tenho!
O meu username é saxocat

2021-01-11 22:11 UTC, 0xyw commented on monero-outreach-docs/translations/pt-br/merchants/how_to_accept_monero_pt_br.md
> +Como alternativa, um processador de pagamento Monero de terceiros terá softwares, aplicativos e interfaces que simplificam a configuração. Eles também terão interfaces e ferramentas para você gerenci
my fault on making this suggestion outdated @lh1008 

```suggestion
Como alternativa, um processador de pagamento Monero de terceiros terá softwares, aplicativos e interfaces que simplificam a configuração. Eles também terão interfaces e ferramentas para você gerenciar sua conta e suporte técnico ao cliente. Consulte nosso guia de [Processadores de Pagamentos Monero](https://www.monerooutreach.org/merchants/monero-payment-processor-guide.html) para obter ajuda para decidir qual configuração é a certa para você.
```

2021-01-11 22:38 UTC, 0xyw commented
I think it's ok now.

2021-01-11 23:14 UTC, botoserelepe approved these changes

2021-01-12 16:20 UTC, lh1008 approved these changes
Thank you @0xyw, @saxocat, and @botoserelepe, great work. This should be ready for merge then.

2021-01-14 19:45 UTC, merged