Create your_privacy_es.md
monero-ecosystem/outreach-docs pull request #274
Opened 2021-01-21 15:05 UTC by dilubit

2021-01-21 15:09 UTC, dilubit commented
@quagmir3 - The translation is ready for your review

2021-01-21 16:14 UTC, quagmir3 requested changes
Your translation has been reviewed. @dilubit

2021-01-21 16:14 UTC, quagmir3 commented on monero-outreach-docs/translations/es/website-sections/your_privacy_es.md
> +Los datos que nos proporcionas cuando intercambiamosmensajes a través del sitio se almacenan en nuestro servidor y luego se eliminan una vez recibidos o respondidos. Si debemos conservarlo como refer
Línea 19. Se te ha escapado un espacio en "intercambiamosmensajes". Sería "intercambiamos mensajes".

2021-01-21 16:14 UTC, quagmir3 commented on monero-outreach-docs/translations/es/website-sections/your_privacy_es.md
> +Siempre que tengamos que pedirte información, se tomarán las mismas precauciones que se indicaron anteriormente. En cada formulario seremos claros qué datos se almacenan y cómo se utilizarán.
Línea 22. Añadiría "con" antes de "qué datos", quedando algo como "seremos claros con qué datos se almacenan".

2021-01-21 16:14 UTC, quagmir3 commented on monero-outreach-docs/translations/es/website-sections/your_privacy_es.md
> +**Actualizaciones & Notificaciones **
Línea 24. Has añadido un espacio en el título a la derecha de "Notificaciones" y no se visualiza como debería.

2021-01-21 16:14 UTC, quagmir3 commented on monero-outreach-docs/translations/es/website-sections/your_privacy_es.md
> +Cualquier otro cambio en lo que estemos haciendo se publicará aquí. Esta página se actualizó en 1609798950 (Unix Epoch) y nunca hemos recibido una citación ni nos hemos visto obligados a cumplir con
Línea 26. Te ha faltado la tilde en la u en la palabra ningún.

2021-01-21 16:35 UTC, dilubit reviewed
I agree with the changes proposed.

2021-01-21 16:35 UTC, dilubit commented on monero-outreach-docs/translations/es/website-sections/your_privacy_es.md
> +Los datos que nos proporcionas cuando intercambiamosmensajes a través del sitio se almacenan en nuestro servidor y luego se eliminan una vez recibidos o respondidos. Si debemos conservarlo como refer
done

2021-01-21 16:35 UTC, dilubit commented on monero-outreach-docs/translations/es/website-sections/your_privacy_es.md
> +Siempre que tengamos que pedirte información, se tomarán las mismas precauciones que se indicaron anteriormente. En cada formulario seremos claros qué datos se almacenan y cómo se utilizarán.
Aqui en realidad hace referencia al tipo de datos que se van a almacenar (IP, pantalla, etc) no con qué se lo almacena

2021-01-21 16:36 UTC, dilubit commented on monero-outreach-docs/translations/es/website-sections/your_privacy_es.md
> +Cualquier otro cambio en lo que estemos haciendo se publicará aquí. Esta página se actualizó en 1609798950 (Unix Epoch) y nunca hemos recibido una citación ni nos hemos visto obligados a cumplir con
Done

2021-01-21 16:37 UTC, dilubit commented on monero-outreach-docs/translations/es/website-sections/your_privacy_es.md
> +**Actualizaciones & Notificaciones **
Este es un commit antiguo. En el siguiente corregí el espacio. gracias

2021-01-23 00:31 UTC, lh1008 approved these changes
Great translation. Thank you @dilubit and @quagmir3 for the review. 

:)

2021-01-23 11:03 UTC, merged