Monero Patents transalation ready to be reviewed
monero-ecosystem/outreach-docs pull request #297
Opened 2021-04-30 14:33 UTC by quagmir3

2021-05-27 20:54 UTC, quagmir3 commented
translation has been updated

2021-05-28 20:42 UTC, lh1008 requested changes
There are two paragraphs that need some updates in links and the word used for wallet "monedero".

2021-05-28 20:44 UTC, lh1008 commented on monero-outreach-docs/translations/es/merchants/how_to_accept_monero_en.md
> +- Cómo aceptar Monero con las billeteras oficiales: [getmonero.org/get-started/accepting](https://www.getmonero.org/get-started/accepting/)
Cómo aceptar Monero con **los monederos** oficiales: [**getmonero.org/es/get-started/accepting**](https://www.getmonero.org/es/get-started/accepting/index.html)

Missed this one too, **"los monederos"** and the link for the Spanish getmonero site -> https://www.getmonero.org/es/get-started/accepting/index.html

2021-05-28 21:45 UTC, lh1008 requested changes
Found one minor change and a link update but I'll do the link update in another commit.

2021-05-28 21:45 UTC, lh1008 commented on monero-outreach-docs/translations/es/storyboard/patents_es.md
> +Las patentes en EE.UU. son o de Utilidad (es decir, cómo funciona una invento) o de Diseño (es decir, cómo se ve un diseño en particular). La mayoría de las patentes de software son de Utilidad. Una
It's in bold, "un".

2021-05-28 21:47 UTC, lh1008 requested changes
Here, missing the link.

2021-05-28 21:47 UTC, lh1008 commented on monero-outreach-docs/translations/es/storyboard/patents_es.md
> +A menudo, es mejor evitar los litigios, ya que el costo promedio de los litigios de patentes es de millones de dólares [8]. Además, el propietario de una patente que presenta una demanda corre un rie
A menudo, es mejor evitar los litigios, ya que el costo promedio de los litigios de patentes es de millones de dólares [[**8**](https://www.monerooutreach.org/stories/monero-patents.html#b8)]. Además, el propietario de una patente que presenta una demanda corre un riesgo significativo porque el demandado puede localizar tecnologías y publicaciones preexistentes que invalidan la patente. Si tal esfuerzo tiene éxito, el propietario de la patente puede quedarse con grandes facturas legales y una patente inválida.

Missing the link for 8 -> https://www.monerooutreach.org/stories/monero-patents.html#b8

2021-05-30 22:12 UTC, closed without merging